chore: bin/test returns 0 iff all tests pass

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,4 +1,9 @@
 #!/usr/bin/env -S sh -eu
+EXITCODE=0
 for TEST in $(find src/test -type f -name '*.sh'); do
-    sh -c ". $TEST"
+    if ! sh -c ". $TEST"; then
+        echo "ERROR: $TEST"
+        EXITCODE=1
+    fi
 done
+exit $EXITCODE
